<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />



<title>Chapter 5: Sampling and Surveys</title>

<script src="ch5_files/jquery-1.11.0/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link href="ch5_files/bootstrap-2.3.2/css/bootstrap.min.css" rel="stylesheet" />
<link href="ch5_files/bootstrap-2.3.2/css/bootstrap-responsive.min.css" rel="stylesheet" />
<script src="ch5_files/bootstrap-2.3.2/js/bootstrap.min.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<link rel="stylesheet"
      href="ch5_files/highlight/default.css"
      type="text/css" />
<script src="ch5_files/highlight/highlight.js"></script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>


<link rel="stylesheet" href="css/coursenotes.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
</style>
<div class="container-fluid main-container">


<div id="header">
<h1 class="title">Chapter 5: Sampling and Surveys</h1>
</div>

<div id="TOC">
<ul>
<li><a href="#introduction">Introduction</a></li>
<li><a href="#population-versus-sample">Population versus Sample</a></li>
<li><a href="#types-of-samples">Types of Samples</a><ul>
<li><a href="#random-sampling">Random Sampling</a><ul>
<li><a href="#simple-random-sample">Simple Random Sample</a></li>
<li><a href="#systematic-sample">Systematic Sample</a></li>
<li><a href="#stratified-sample">Stratified Sample</a></li>
<li><a href="#cluster-sample">Cluster Sample</a></li>
</ul></li>
<li><a href="#comparison-of-sampling-methods">Comparison of Sampling Methods</a></li>
</ul></li>
<li><a href="#bias-in-surveys">Bias in Surveys</a><ul>
<li><a href="#selection-bias">Selection Bias</a></li>
<li><a href="#nonresopnse-bias">Nonresopnse Bias</a></li>
<li><a href="#response-bias">Response Bias</a></li>
</ul></li>
<li><a href="#thoughts-on-r">Thoughts on R</a></li>
</ul>
</div>

<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>Recall from Chapter 3 that most research questions actually break down into 2 parts:</p>
<ul>
<li><p><strong>Descriptive Statistics</strong>: What relationship can we observe between the variables, <em>in the sample</em>?</p></li>
<li><p><strong>Inferential Statistics</strong>: Supposing we see a relationship in the sample data, how much evidence is provided for a relationship <em>in the population</em>? Does the data provide lots of evidence for a relationship in the population, or could the relationship we see in the sample be due just to chance variation in the sampling process that gave us the data?</p></li>
</ul>
<p>Both parts of answering research questions involve dealing with the sample. In order to make valid conclusions about any research question, we first need to make sure we are dealing with a <em>good</em> sample. This chapter will discuss various techniques for drawing samples, the strengths and weaknesses of these sampling techniques, and the uses and abuses of statistics.</p>
</div>
<div id="population-versus-sample" class="section level1">
<h1>Population versus Sample</h1>
<p>In the past few of chapters, we have looked at both parts of research questions. An important distinction that we want to make sure has been made before we go any further is the distinction between a <strong>sample</strong> and a <strong>population</strong>.</p>
<dl>
<dt>Population</dt>
<dd><p>A <em>population</em> is the set of all subjects of interest.</p>
</dd>
<dt>Sample</dt>
<dd><p>A <em>sample</em> is the subset of the population for which we have data.</p>
</dd>
</dl>
<p>Let’s consider these two definitions with a research question.</p>
<blockquote>
<p><strong>Research Question</strong>: In the United States, what is the mean height of adult males (18 years +)?</p>
</blockquote>
<p>The <em>population</em> that we are dealing with in this case is all U.S. adult males. One way to find an exact answer to this research question would be to survey the entire population. However, this is nearly impossible! It would be much quicker and easier to measure only a subset of the population, a <em>sample</em>.</p>
<p>However, if we want our sample to be an accurate reflection of the population, we can’t just choose <em>any</em> sample that we wish. The way in which we collect our <strong>sample</strong> is very important and will be a topic of conversation in this chapter.</p>
<p>For the time being, let’s suppose that we were able to choose an appropriate sample (and we’ll talk more about how this is done later). Suppose that our sample of U.S. men is an accurate representation of the U.S. population of men. Then, we might discuss two different means: the <em>mean height of the sample</em> and the <em>mean height of the population</em>. These are both <strong>descriptions</strong>, as opposed to <strong>inferences</strong>. There are a couple of differences, however.</p>
<p><em>Mean Height of the Sample</em></p>
<ul>
<li>Statistic - describes the sample</li>
<li>Can be known, but it changes depending on the sample</li>
<li>Symbol - <span class="math">\(\bar{x}\)</span> (pronounced “x bar”)</li>
</ul>
<p><em>Mean Height of the Population</em></p>
<ul>
<li>Parameter - describes the population</li>
<li>Usually unknown - but we wish we knew it!</li>
<li>Symbol - <span class="math">\(\mu\)</span> (pronounced “mu”)</li>
</ul>
<p>Our goal is to use the information we’ve gathered from the <em>sample</em> to <strong>infer</strong>, or <strong>predict</strong>, something about the <em>population</em>. For our example, we want to predict the population mean, using our knowledge of the sample. The accuracy of our <em>sample mean</em> relies heavily upon how well our <em>sample</em> represents the <em>population</em> at large. If our sample does a poor job at representing the population, then any inferences that we make about the population are also going to be poor. Thus, it is very important to select a good sample!</p>
<p><strong>Note</strong>: If we already knew everything about a population, it would be useless to gather a sample in order to <em>infer</em> something about the population. We would already have this information! Using statistics as an <em>inferential</em> tool means that you don’t have information about the entire population to start with. If you are able to sample the entire population, this would be called a <strong>census</strong>.</p>
<p>It would be nice to see what a sample looks like in comparison to the population from which it is drawn. In <code>tigerstats</code> we have a dataset that represents an imaginary population, <code>imagpop</code>. Drawing samples from this “population” will help give an idea of the distinction between <em>sample</em> versus <em>population</em> and <em>statistic</em> versus <em>parameter</em>. Try out the following app, keeping in mind that information about the sample is displayed in <em>light blue</em> and information about the population is displayed in <em>red</em>.</p>
<pre class="r"><code>require(manipulate)
SimpleRandom()</code></pre>
</div>
<div id="types-of-samples" class="section level1">
<h1>Types of Samples</h1>
<p>There are 2 main kinds of sampling:</p>
<ul>
<li><p>Random Sampling</p></li>
<li><p>Non-Random Sampling</p></li>
</ul>
<p>There are advantages and disadvantages of both.</p>
<div id="random-sampling" class="section level2">
<h2>Random Sampling</h2>
<p>There are four different methods of random sampling that we will discuss in this chapter:</p>
<ul>
<li><strong>Simple Random Sampling (SRS)</strong></li>
<li><strong>Systematic Sampling</strong></li>
<li><strong>Stratified Sampling</strong></li>
<li><strong>Cluster Sampling</strong></li>
</ul>
<p>The simple random sample (SRS) is the type of sample that we will focus most of our attention on in this class. However, the other types have been included in the text to give you comparisons to the SRS and also to aid you in the future.</p>
<p>It will be helpful to work with an example as we describe each of these methods, so let’s use the following set of 28 students from FakeSchool as our population from which we will sample.</p>
<pre class="r"><code>data(FakeSchool)
View(FakeSchool)
help(FakeSchool)</code></pre>
<p>Keep in mind that we would not know information about an entire population in real life! <strong>We are using this “population” for demonstration purposes only!</strong></p>
<p>Our goal is to describe how these different sampling techniques are implemented, the strengths and weaknesses of them, and to form a comparison between the techniques. We will try to answer the following question:</p>
<blockquote>
<p>Which random sampling method (<em>simple random sample</em>, <em>systematic sample</em>, <em>stratified sample</em>, or <em>cluster sample</em>) is the most appropriate for estimating the mean grade point average (GPA) for the students at FakeSchool?</p>
</blockquote>
<p>We can easily compute the true mean GPA for the students at FakeSchool by averaging the values in the fourth column of the dataset. This will be the <strong>population mean</strong>. We will call it <span class="math">\(\mu\)</span> (“mu”).</p>
<pre class="r"><code>mu &lt;- mean(~GPA,data=FakeSchool)
mu</code></pre>
<pre><code>## [1] 2.766429</code></pre>
<p>Again, the population parameter, <span class="math">\(\mu\)</span>, is not typically known. If it were known, there would be no reason to estimate it! However, the point of this example is to practice selecting different types of samples and to compare the performance of these different sampling techniques.</p>
<div id="simple-random-sample" class="section level3">
<h3>Simple Random Sample</h3>
<dl>
<dt>Simple Random Sampling (SRS)</dt>
<dd>In <em>simple random sampling</em>, for a given sample size <span class="math">\(n\)</span> every set of <span class="math">\(n\)</span> members of the population has the same chance to be the sample that is actually selected.
</dd>
</dl>
<p>We often use the acronym SRS as an abbreviation for “simple random sampling”.</p>
<p>Intuitively, let’s think of simple random sampling as follows: we find a big box, and for each member of the population we put into the box a ticket that has the name of the individual written on it. All tickets are the same size and shape. Mix up the tickets thoroughly in the box. Then pull out a ticket at random, set it aside, pull out another ticket, set it aside, and so on until the desired number of tickets have been selected.</p>
<p>Let’s select a <em>simple random sample</em> of 7 elements without replacement. We can accomplish this easily with the built in function <code>popsamp</code> in R. This function requires two pieces of information:</p>
<ul>
<li>the size of the sample</li>
<li>the dataset from which to draw the sample</li>
</ul>
<p>Remember that sampling <em>without replacement</em> means that once we draw an element from the population, we do not put it back so that it can be drawn again. We would not want to draw with replacement as this could possibly result with a sample containing the same person more than once. This would not be a good representation of the entire school. (By default, the <code>popsamp</code> function always samples without replacement. If you want to sample with replacement, you would need to add a third argument to the function: <code>replace=TRUE</code>. Typically, we will sample without replacement in this class.)</p>
<p>Since we may want to access this sample later, it’s a good idea to store our sample in an object.</p>
<pre class="r"><code>set.seed(314159)
srs &lt;- popsamp(7,FakeSchool)
srs</code></pre>
<pre><code>##    Students Sex class  GPA Honors
## 6       Eva   F    Fr 1.80     No
## 18    Derek   M    Jr 3.10    Yes
## 7     Georg   M    Fr 1.40     No
## 11    Dylan   M    So 3.50    Yes
## 23      Bob   M    Sr 3.80    Yes
## 13     Eric   M    So 2.10     No
## 14  Gabriel   M    So 1.98     No</code></pre>
<p>Let’s calculate the mean GPA for the 7 sampled students. This will be the <em>sample mean</em>, <span class="math">\(\bar{x}_{srs}\)</span>. We will use the subscript ‘srs’ to remind ourselves that this is the sample mean for the simple random sample.</p>
<pre class="r"><code>xbar.srs &lt;- mean(~GPA,data=srs)
xbar.srs</code></pre>
<pre><code>## [1] 2.525714</code></pre>
<p><em>Strengths</em></p>
<ul>
<li><p>The selection of one element does not affect the selection of others.</p></li>
<li><p>Each possible sample, of a given size, has an equal chance of being selected.</p></li>
<li><p>Simple random samples tend to be good representations of the population.</p></li>
<li><p>Requires little knowledge of the population.</p></li>
</ul>
<p><em>Weaknesses</em></p>
<ul>
<li><p>If there are small subgroups within the population, a SRS may not give an accurate representation of that subgroup. In fact, it may not include it at all! This is especially true if the sample size is small.</p></li>
<li><p>If the population is large and widely dispersed, it can be costly (both in time and money) to collect the data.</p></li>
</ul>
</div>
<div id="systematic-sample" class="section level3">
<h3>Systematic Sample</h3>
<dl>
<dt>Systematic Sampling</dt>
<dd>In a <em>systematic sample</em>, the members of the population are put in a row. Then 1 out of every <span class="math">\(k\)</span> members are selected. The starting point is randomly chosen from the first <span class="math">\(k\)</span> elements and then elements are sampled at the same location in each of the subsequent segments of size <span class="math">\(k\)</span>.
</dd>
</dl>
<p>To illustrate the idea, let’s take a 1-in-4 systematic sample from our FakeSchool population.</p>
<p>We will start by randomly selecting our starting element.</p>
<pre class="r"><code>set.seed(49464)
start=sample(1:4,1)
start</code></pre>
<pre><code>## [1] 4</code></pre>
<p>So, we will start with element 4, which is Daisy and choose every 4th element after that for our sample.</p>
<pre><code>##    Students Sex class GPA Honors
## 4     Daisy   F    Fr 2.1     No
## 8    Andrea   F    So 4.0    Yes
## 12   Felipe   M    So 3.0     No
## 16 Brittany   F    Jr 3.9     No
## 20   Eliott   M    Jr 1.9     No
## 24     Carl   M    Sr 3.1     No
## 28    Grace   F    Sr 1.4     No</code></pre>
<p>The mean GPA of the systematic sample, the <em>sample mean</em>, <span class="math">\(\bar{x}_{sys}\)</span>, is 2.7714286.</p>
<p><em>Strengths</em></p>
<ul>
<li><p>Assures an even, random sampling of the population.</p></li>
<li><p>When the population is an <em>ordered</em> list, a systematic sample gives a better representation of the population than a SRS.</p></li>
<li><p>Can be used in situations where a SRS is difficult or impossible. It is especially useful when the population that you are studying is arranged in time.</p></li>
</ul>
<p>For example, suppose you are interested in the average amount of money that people spend at the grocery store on a Wednesday evening. A <em>systematic sample</em> could be used by selecting every 10th person that walks into the store.</p>
<p><em>Weaknesses</em></p>
<ul>
<li><p>Not every combination has an equal chance of being selected. Many combinations will never be selected using a systematic sample!</p></li>
<li><p>Beware of <em>periodicity</em> in the population! If, after ordering, the selections match some pattern in the list (skip interval), the sample may not be representative of the population.</p></li>
</ul>
<p>The list of the FakeSchool students is ordered according to the student’s year in school (freshmen, sophomore, junior, senior). Taking a systematic sample ensures that we have a person from each class represented in our sample. However, there is an underlying pattern, or periodicity, in the data. The students are also listed according to their GPA. For instance, Alice is ranked first in the freshmen class and George is ranked last in the freshmen class.</p>
<p>Consider what would have happened if we had used a <em>systematic sample</em> of 4 students to estimate the average GPA of the students at the school.</p>
<pre><code>##    Students Sex class  GPA Honors
## 1     Alice   F    Fr 3.80    Yes
## 8    Andrea   F    So 4.00    Yes
## 15     Adam   M    Jr 3.98    Yes
## 22   Angela   F    Sr 4.00    Yes</code></pre>
<p>Notice that even thought the <em>systematic sample</em> ensured that we got one person from each class, we also ended up getting students of the same class rank due to the underlying pattern. Our estimate for the average GPA is not going to truly reflect the population of the school! It may be <strong>biased</strong> since the GPA pattern coincided with the skip interval.</p>
</div>
<div id="stratified-sample" class="section level3">
<h3>Stratified Sample</h3>
<dl>
<dt>Stratified Sampling</dt>
<dd>In a <em>stratified sample</em>, the population must first be separated into homogeneous groups, or <em>strata</em>. Each element only belongs to one stratum and the stratum consist of elements that are alike in some way. A simple random sample is then drawn from each stratum, which is combined to make the stratified sample.
</dd>
</dl>
<p>Let’s take a stratified sample of 7 elements from FakeSchool using the following strata: Honors, Not Honors. First, let’s determine how many elements belong to each strata:</p>
<pre><code>## Honors
##  No Yes 
##  16  12</code></pre>
<p>So there are 12 Honors students at FakeSchool and 16 non-Honors students at FakeSchool.</p>
<p>There are various ways to determine how many students to include from each stratum. For example, you could choose to select the same number of students from each stratum. Another strategy is to use a <em>proportionate stratified sample</em>. In a <em>proportionate stratified sample</em>, the number of students selected from each stratum is proportional to the representation of the strata in the population. For example, <span class="math">\(\frac{12}{28}\)</span> X 100% = 42.8571429% of the population are Honors students. This means that there should be 0.4285714 X 7 = 3 Honors students in the sample. So there should be 7-3=4 non-Honors students in the sample.</p>
<p>Let’s go through the coding to draw these samples. Check out the how we use the <code>subset</code> function to pull out the Honors students from the rest of the populations:</p>
<pre class="r"><code>set.seed(1837)
honors=subset(FakeSchool,Honors==&quot;Yes&quot;)
honors</code></pre>
<pre><code>##    Students Sex class  GPA Honors
## 1     Alice   F    Fr 3.80    Yes
## 2      Brad   M    Fr 2.60    Yes
## 8    Andrea   F    So 4.00    Yes
## 9     Betsy   F    So 4.00    Yes
## 10    Chris   M    So 4.00    Yes
## 11    Dylan   M    So 3.50    Yes
## 15     Adam   M    Jr 3.98    Yes
## 17   Cassie   F    Jr 3.75    Yes
## 18    Derek   M    Jr 3.10    Yes
## 19    Faith   F    Jr 2.50    Yes
## 22   Angela   F    Sr 4.00    Yes
## 23      Bob   M    Sr 3.80    Yes</code></pre>
<p>Next, we take a SRS of size 3 from the Honors students:</p>
<pre class="r"><code>honors.samp=popsamp(3,honors)
honors.samp</code></pre>
<pre><code>##    Students Sex class GPA Honors
## 9     Betsy   F    So 4.0    Yes
## 11    Dylan   M    So 3.5    Yes
## 8    Andrea   F    So 4.0    Yes</code></pre>
<p>The same method will work for non-Honors students.</p>
<pre class="r"><code>set.seed(17365)
nonhonors=subset(FakeSchool,Honors==&quot;No&quot;) 
nonhonors.samp=popsamp(4,nonhonors) 
nonhonors.samp</code></pre>
<pre><code>##    Students Sex class  GPA Honors
## 25    Diana   F    Sr 2.90     No
## 13     Eric   M    So 2.10     No
## 14  Gabriel   M    So 1.98     No
## 28    Grace   F    Sr 1.40     No</code></pre>
<p>We can put this together to create our stratified sample.</p>
<pre><code>##    Students Sex class  GPA Honors
## 9     Betsy   F    So 4.00    Yes
## 11    Dylan   M    So 3.50    Yes
## 8    Andrea   F    So 4.00    Yes
## 25    Diana   F    Sr 2.90     No
## 13     Eric   M    So 2.10     No
## 14  Gabriel   M    So 1.98     No
## 28    Grace   F    Sr 1.40     No</code></pre>
<p>The sample mean for the stratified sample, <span class="math">\(\bar{x}_{strat}\)</span>, is 2.84.</p>
<p><em>Strengths</em></p>
<ul>
<li><p>Representative of the population, because elements from all strata are included in the sample.</p></li>
<li><p>Ensures that specific groups are represented, sometimes even proportionally, in the sample.</p></li>
<li><p>Since each stratified sample will be distributed similarly, the amount of variability between samples is decreased.</p></li>
<li><p>Allows comparisons to be made between strata, if necessary. For example, a stratified sample allows you to easily compare the mean GPA of Honors students to the mean GPA of non-Honors students.</p></li>
</ul>
<p><em>Weaknesses</em></p>
<ul>
<li>Requires prior knowledge of the population. You have to know something about the population to be able to split into strata!</li>
</ul>
</div>
<div id="cluster-sample" class="section level3">
<h3>Cluster Sample</h3>
<dl>
<dt>Cluster Sampling</dt>
<dd><em>Cluster sampling</em> is a sampling method used when natural groups are evident in the population. The clusters should all be similar each other: each cluster should be a small scale representation of the population. To take a <strong>cluster sample</strong>, a random sample of the clusters is chosen. The elements of the randomly chosen clusters make up the sample.
</dd>
</dl>
<p><strong>Note</strong>: There are a couple of differences between stratified and cluster sampling.</p>
<ul>
<li><p>In a stratified sample, the differences <em>between</em> stratum are high while the differences <em>within</em> strata are low. In a cluster sample, the differences <em>between</em> clusters are low while the differences <em>within</em> clusters are high.</p></li>
<li><p>In a stratified sample, a simple random sample is chosen from <em>each</em> stratum. So, all of the stratum are represented, but not all of the elements in each stratum are in the sample . In a cluster sample, a simple random sample of clusters is chosen. So, not all of the clusters are represented, but all elements from the chosen clusters are in the sample.</p></li>
</ul>
<p>Let’s take a cluster sample using the grade level (freshmen, sophomore, junior, senior) of FakeSchool as the clusters. Let’s take a random sample of 2 of them.</p>
<pre><code>##    Students Sex class  GPA Honors
## 15     Adam   M    Jr 3.98    Yes
## 16 Brittany   F    Jr 3.90     No
## 17   Cassie   F    Jr 3.75    Yes
## 18    Derek   M    Jr 3.10    Yes
## 19    Faith   F    Jr 2.50    Yes
## 20   Eliott   M    Jr 1.90     No
## 21    Garth   M    Jr 1.10     No
## 22   Angela   F    Sr 4.00    Yes
## 23      Bob   M    Sr 3.80    Yes
## 24     Carl   M    Sr 3.10     No
## 25    Diana   F    Sr 2.90     No
## 26    Frank   M    Sr 2.00     No
## 27       Ed   M    Sr 1.50     No
## 28    Grace   F    Sr 1.40     No</code></pre>
<p>The sample mean for the clustered sample, <span class="math">\(\bar{x}_{clust}\)</span>, is 2.7807143.</p>
<p><em>Strengths</em></p>
<ul>
<li>Makes it possible to sample if there is no list of the entire population, but there is a list of subpopulations. For example, there is not a list of <strong>all</strong> church members in the United States. However, there is a list of churches that you could sample and then acquire the members list from each of the selected churches.</li>
</ul>
<p><em>Weaknesses</em></p>
<ul>
<li>Not always representative of the population. Elements within clusters tend to be similar to one another based on some characteristic(s). This can lead to over-representation or under-representation of those characteristics in the sample.</li>
</ul>
</div>
</div>
<div id="comparison-of-sampling-methods" class="section level2">
<h2>Comparison of Sampling Methods</h2>
<p>Now that you have an idea about how to take each of these kinds of samples, let’s compare them by doing repeated samples. There is no general rule for determining which sampling method is best. The choice of sampling method depends on the data that is being analyzed and will require the statistician’s judgment.</p>
<p>We will compare the <em>simple random sample</em> and the <em>systematic sample</em> by determining which sample produces the <strong>least variable mean GPA estimate</strong> after repeated sampling.</p>
<p>Putting that another way: Let’s start by taking 1000 simple random samples and 1000 systematic samples. We will compute <span class="math">\(\bar{x}_{srs}\)</span> and <span class="math">\(\bar{x}_{sys}\)</span> for each of the samples. Then, these sample means will be compared using some graphical and numerical summaries (specifically standard deviation) that you learned about in Chapter 2.</p>
<p>We’re going to take the SRS’s and systematic samples just like did before. The only difference is that now we’ll be taking 1000 of them instead of just 1. Since we only care about the sample mean for each sample, we’ll create a boxplot of the <span class="math">\(\bar{x}_{srs}\)</span>’s and a boxplot of the <span class="math">\(\bar{x}_{sys}\)</span>’s. These two boxplots allow us to compare the amount of variation, or spread, in the estimates for the mean GPA generated from the two different sampling methods (SRS and systematic sampling). See Figure[Boxplots].</p>
<p><img src="ch5_files/figure-html/boxplots-1.png" alt="Boxplots: Compare the mean GPA estimates from the 1000 simple random samples to the mean GPA estimates from the 1000 systematic samples." /> <img src="ch5_files/figure-html/boxplots-2.png" alt="Boxplots: Compare the mean GPA estimates from the 1000 simple random samples to the mean GPA estimates from the 1000 systematic samples." /></p>
<p>To support this visualization of the variability of the mean estimate for GPA, let’s also look at <code>favstats</code>. For the 1000 simple random samples, the numerical summaries of the sample means is:</p>
<pre><code>##       min       Q1 median       Q3 max     mean        sd    n missing
##  1.785714 2.556429  2.765 2.985714 3.7 2.768701 0.3173966 1000       0</code></pre>
<p>For the 1000 systematic samples, the numerical summaries of the sample means is:</p>
<pre><code>##  min      Q1 median    Q3   max    mean       sd    n missing
##  2.9 3.18125  3.425 3.575 3.945 3.42042 0.381641 1000       0</code></pre>
<p>Recall that the true average GPA for the population of students at FakeSchool was 2.7664286. Notice that the average value for the sample means from the 1000 simple random samples is 2.7687014. This is pretty close to the population parameter. (We will talk about what “pretty close” means in later chapters.) Compare this to the average value for the sample means from the 1000 systematic samples: 3.42042. On average, the SRS does a better job of producing an estimate for the mean GPA than the systematic sample.</p>
<p>Additionally, there is less variability in the 1000 <span class="math">\(\bar{x}_{srm}\)</span>’s (0.3173966) than in the 1000 <span class="math">\(\bar{x}_{sys}\)</span>’s (0.381641).</p>
<p>If we could only pick one of these types of samples to estimate the mean GPA, it appears the a SRS is a better choice than a systematic sample.</p>
<p>Let’s do a similar analysis to compare the two sampling methods, <em>stratified sampling</em> or <em>cluster sampling</em>. We will compare the <em>stratified sample</em> and the <em>cluster sample</em> by determining which sample produces the <strong>least variable mean GPA estimate</strong> after repeated sampling.</p>
<p><img src="ch5_files/figure-html/boxplots2-1.png" alt="Boxplots2: Compare the mean GPA estimates from the 1000 stratified samples to the mean GPA estimates from the 1000 cluster samples." /> <img src="ch5_files/figure-html/boxplots2-2.png" alt="Boxplots2: Compare the mean GPA estimates from the 1000 stratified samples to the mean GPA estimates from the 1000 cluster samples." /></p>
<p>To support this visualization of the variability of the mean estimate for GPA, let’s also look at <code>favstats</code>. For the 1000 stratified samples, the numerical summaries of the sample means is:</p>
<pre><code>##   min       Q1   median       Q3      max     mean        sd    n missing
##  2.14 2.620714 2.768571 2.921429 3.422857 2.772663 0.2215186 1000       0</code></pre>
<p>For the 1000 cluster samples, the numerical summaries of the sample means is:</p>
<pre><code>##    min       Q1   median       Q3      max     mean        sd    n missing
##  2.475 2.584286 2.752143 2.948571 3.057857 2.762486 0.1965341 1000       0</code></pre>
<p>Both of these sampling methods produce an average of the sample means that is pretty close to the true mean GPA for the population. However, the sample means from the clustered samples have less variability. (This can be seen by comparing the standard deviations.) In other words, the 1000 cluster samples are closer, on average, to the true mean than the 1000 stratified samples.</p>
<p>If we could only pick one of these types of samples to estimate the mean GPA, it appears the cluster sample is a better choice than a stratified sample.</p>
</div>
</div>
<div id="bias-in-surveys" class="section level1">
<h1>Bias in Surveys</h1>
<dl>
<dt>Bias</dt>
<dd>We say that a sampling method is <em>biased</em> if it exhibits a systematic tendency to result in samples that do not reflect the population, in some important respect.
</dd>
</dl>
<p>You can think of a survey as occurring in three stages:</p>
<ol style="list-style-type: decimal">
<li>Select subjects to invite into your sample. this is the <em>sampling</em> stage.</li>
<li>Get them to accept your invitation. This is the stage where you contact the subjects you have sampled, and ask them to participate in your survey.</li>
<li>Obtain their responses to your questions.</li>
</ol>
<p>At each of these stages, some bias can creep in!</p>
<div id="selection-bias" class="section level2">
<h2>Selection Bias</h2>
<p>Selection bias is the type of bias that can occur in the first stage, in which you are selecting the subjects who will be your sample.</p>
<dl>
<dt>Selection Bias</dt>
<dd>We say that a sampling method exhibits <em>selection bias</em> if its mechanism for selecting the sample has a systematic tendency to over-represent or under-represent a particular subset of the population.
</dd>
</dl>
<p>One sampling method that can result in selection bias is convenience sampling.</p>
<dl>
<dt>Convenience Sampling</dt>
<dd><em>Convenience sampling</em> is the practice of sampling subjects that the researcher can reach easily. This may result in certain subgroups of the population being underrepresented or completely left out.
</dd>
</dl>
<p><strong>Example:</strong> A math professor wants to know what percentage of young adults, ages 18-22, consider education a top priority. She gathers a sample by surveying all of her advisees.</p>
<p>This method of sampling is quick and easy. However, only including students that are enrolled in college leaves out a large part of the population - those young adults that did not go to college or enrolled in a different type of higher education. Only including college students in this study might make it appear that a high percentage of young adults consider education a top priority. The subjects in the study surely consider it a priority since they are seeking a college degree.</p>
<p>Another form of selection bias occurs when you attempt to sample everyone in the population, but you leave it up to each member of the population to find out about your survey and to take part in it. This is called “volunteer” sampling.</p>
<dl>
<dt>Volunteer Sampling</dt>
<dd>A <em>volunteer sample</em> is a sample of only those subjects that have volunteered to be part of a study. There may be common characteristics about the people that volunteer to be part of a particular survey that creates bias.
</dd>
</dl>
<p><strong>Example:</strong> A radio station wishes to examine the proportion of its listeners which candidate they voted for in the last presidential election. They conduct a poll by asking listeners to call the station.</p>
<p>Conducting a survey in this manner is also quick and easy, but there are groups in the population that are <em>underrepresented</em> or <em>not represented at all</em>! Only those listeners who want to disclose this information will be part of the survey. Those volunteers may have something else in common that will bias the results: for example, they may have stronger opinions on the question at hand than do other folks who did not choose to go out of their way to phone in their thoughts.</p>
<p>One great advantage of the simple random sampling and proportionate stratified sampling – two of the methods we discussed earlier – is that they are not subject to selection bias.</p>
</div>
<div id="nonresopnse-bias" class="section level2">
<h2>Nonresopnse Bias</h2>
<p>Even if you succeed in selecting a sample of subjects in an unbiased way, you still face the task of acquiring their consent to be in your survey. Some people may refuse to take part, or perhaps you will be unable to contact them all. In that event, they won’t respond to the survey, and this could lead to bias.</p>
<dl>
<dt>Nonresponse Bias</dt>
<dd>We say that a sampling method exhibits <em>nonresponse bias</em> if there is a systematic tendency for the people who elect to take part in the survey to differ from the population in some important way.
</dd>
</dl>
<p><strong>Example:</strong> The faculty at Georgetown College wanted to know what proportion of students thought that Foundations should be required for all freshmen. A simple random sample of 200 students was selected from a list obtained from the registrar. A survey form was sent by email to those students. After analyzing the results from the 20 people that reply, the faculty report that 90% of the students oppose the requirement for Foundations.</p>
<ul>
<li>What was the population?</li>
</ul>
<blockquote>
<p><strong>Answer:</strong> The population of interest is the entire student body at Georgetown College.</p>
</blockquote>
<ul>
<li>What was the intended sample size?</li>
</ul>
<blockquote>
<p><strong>Answer:</strong> The intended sample size was 200.</p>
</blockquote>
<ul>
<li>What was the sample size actually observed?</li>
</ul>
<blockquote>
<p><strong>Answer:</strong> The sample size that was actually observed was the number of students that responded to the survey, 20.</p>
</blockquote>
<ul>
<li>What was the percentage of nonresponse?</li>
</ul>
<blockquote>
<p><strong>Answer:</strong> Since 20 of the 200 students selected for the survey actually respond, 180 did not respond. The percentage of nonresponse was 90%. It can be found by:</p>
</blockquote>
<pre class="r"><code>(180/200)*100  </code></pre>
<pre><code>## [1] 90</code></pre>
<ul>
<li>Why might this cause the results to be <em>biased</em>?</li>
</ul>
<blockquote>
<p><strong>Answer:</strong> If all of the 200 randomly selected students had responded to the survey, we would have had a true SRS. However, nonresponse bias has occurred in this study because 90% of the sampled subjects either <em>were not reached</em>, <em>refused to participate</em>, or <em>failed to answer the question</em>. A couple of possible explanations for the nonresponding students might be that they do not check their email or they simply did not have a strong enough opinion on the topic to feel the need to take the time to respond. (There may be other legitimate reasons.) So, it could be that the students that responded had very strong feelings about the Foundations requirement. If these are the only answers that are acquired, the results may be heavily biased in the direction of the opinion of the respondents. However, this does not mean that all students feel this way.</p>
</blockquote>
</div>
<div id="response-bias" class="section level2">
<h2>Response Bias</h2>
<p>The wording and presentation of the questions can significantly influence the results of a survey. The main type of bias that can result from a poorly-worded survey is <em>response bias</em>.</p>
<dl>
<dt>Response Bias</dt>
<dd>We say that a sampling method exhibits <em>response bias</em> if the way the questions are asked or framed tends to influence the subjects’ responses in a particular way.
</dd>
</dl>
<p>Many things can subject a survey response bias. Here are a few:</p>
<ul>
<li>Deliberate Wording Bias</li>
<li>Unintentional Wording Bias</li>
<li>Desire of the Respondents to Please</li>
<li>Asking the Uninformed</li>
<li>Unnecessary Complexity</li>
<li>Ordering of Questions</li>
<li>Confidentiality Concerns</li>
</ul>
<blockquote>
<p><strong>Deliberate Response Bias</strong> - If a survey is being conducted to support a certain cause, questions are sometimes deliberately worded in a biased manner. The wording of a question should not indicate a desired answer.</p>
</blockquote>
<p><strong>Example:</strong> Consider the following research question: “Seeing as Dr. Robinson and Dr. White are the greatest professors you have ever had, is it worth even offering the peer tutoring sessions for MAT111?”</p>
<p>This question is prefaced in a way that encourages a desired response from the subjects in the study.</p>
<blockquote>
<p><strong>Unintentional Response Bias</strong> - Some questions are worded in such a way that the meaning is misinterpreted by the respondents.</p>
</blockquote>
<p><strong>Example:</strong> Consider the following research question: “Do you use drugs?” The word <em>drugs</em> can cause unintentional confusion for the respondent. The intended definition of drugs is not made clear in the wording of the question. Does the researcher mean illegal drugs, prescription drugs, over the counter drugs, or possibly even caffeine?</p>
<blockquote>
<p><strong>Desire of Respondents to Please</strong> - People may respond differently depending on how they are being asked - face-to-face, over the telephone, on paper, on the internet.</p>
</blockquote>
<p>For example, a person may tend to be more honest when answering questions on paper or over the internet. When speaking directly to the researcher, the respondent may feel the need to answer the question how they perceive the researcher wants.</p>
<blockquote>
<p><strong>Asking the Uninformed</strong> - If a question is about a topic that the respondent does not know anything about, they often do not like to admit it. Respondents may tend to give an answer, even though they do not understand the question.</p>
</blockquote>
<blockquote>
<p><strong>Unnecessary complexity</strong> - Questions should be kept simple. Try to only ask one question at a time.</p>
</blockquote>
<p><strong>Example:</strong> Consider the following survey question: “Most semesters are 15 weeks long; while most quarters are 10 weeks long. Most schools on a quarter system get 2 days for Thanksgiving, one for Veteran’s Day, and one for Columbus Day. Most semester schools get Labor Day off and some take more than 2 days at Thanksgiving. However, semester schools typically start several weeks earlier in the fall and generally attend school farther into December. Considering the above, which system would you prefer?”</p>
<p>This question has too much information in it. By the time you get done reading it, you may have forgotten what the question is even referring to. It is unnecessarily complex!</p>
<blockquote>
<p><strong>Ordering of Questions</strong> - If one question requires respondents to think about something that they may not have otherwise considered, then the order in which questions are presented can change the results.</p>
</blockquote>
<p><strong>Example:</strong> Suppose a researcher wants to know how many hours a day people spend on the Internet. Consider the following sequence of questions:</p>
<ul>
<li>“Do you own a smartphone?”&quot;</li>
<li>“How many hours a day do you spend on the Internet?”</li>
</ul>
<p>Placing the question about the smartphone before the question about time spent on the Internet causes the respondent to take into consideration that they are often on the Internet when they are using their phone. Putting the questions in this order may change the answers received for the second question.</p>
<blockquote>
<p><strong>Confidentiality Concerns</strong> - Some personal questions will be answered differently depending on how confident the respondent is that their identity will be concealed.</p>
</blockquote>
</div>
</div>
<div id="thoughts-on-r" class="section level1">
<h1>Thoughts on R</h1>
<p>Know how to use this function:</p>
<ul>
<li><code>popsamp</code></li>
</ul>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
